// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnFL34S5BSk9rUT3BGatbSbBJ8CaUWUek',
    appId: '1:813883414165:android:84d4efdc4f0ebe1fecad9c',
    messagingSenderId: '813883414165',
    projectId: 'flutter-rpg-e8603',
    storageBucket: 'flutter-rpg-e8603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CWz4Mh7BVPQ7xvCzmHlOqcNphcwuXtU',
    appId: '1:813883414165:ios:7d21bd522efa227cecad9c',
    messagingSenderId: '813883414165',
    projectId: 'flutter-rpg-e8603',
    storageBucket: 'flutter-rpg-e8603.firebasestorage.app',
    iosBundleId: 'com.example.testamSaMearga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGWY5EXjmKFXKcLswMSJbjeXAa6UZq5e8',
    appId: '1:813883414165:web:b48cf6431cc747d6ecad9c',
    messagingSenderId: '813883414165',
    projectId: 'flutter-rpg-e8603',
    authDomain: 'flutter-rpg-e8603.firebaseapp.com',
    storageBucket: 'flutter-rpg-e8603.firebasestorage.app',
  );

}